# Generated by Django 3.1.4 on 2021-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picha', '0002_dog_pics_tech_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_pics',
            name='image',
            field=models.ImageField(upload_to='images/dogs/'),
        ),
        migrations.AlterField(
            model_name='tech_pics',
            name='image',
            field=models.ImageField(upload_to='images/tech/'),
        ),
    ]
